PROXY_WEBSITES :
  US :
    # internal working of fetching proxies for us
    # will fail if this link for PROXY_SITE changed
    # or is not responding
    PROXY_SITE : https://www.us-proxy.org/
    HTTP_TEST : http://www.ritba.org/tolls-2/
    HTTPS_TEST : https://www.mcallen.net/departments/bridge/anzalduas

PROXY_DATAFRAME :
  PATH : proxies.json